baseURL = 'http://127.0.0.1'
languageCode = 'en-us'
title = 'Kevin'
enableMissingTranslationPlaceholders = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[Params.Kevin]
CvSource = 'cv'
Sections = ['Experience', 'Project', 'Certificate', 'Education', 'Skill']
Footer = '''
[Kevin](https://github.com/tnlx/kevin) Hugo theme.
Use `[params.kevin.footer]` to overwrite this text.
'''